[package]
name = "sunna-host"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
sunna-capture.workspace = true
sunna-clipboard.workspace = true
sunna-codec.workspace = true
sunna-audio.workspace = true
sunna-input.workspace = true
sunna-proto.workspace = true
sunna-transport.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
sunna-client.workspace = true
