"""Writes icon.svg: Sunna's app icon on Apple's macOS icon grid.

The body is an 824 px rounded square on a 1024 px canvas (100 px margin
for the shadow), with smoothed ("continuous") corners like Apple's own:
radius 185.4, 60% corner smoothing, after the figma-squircle construction.
Render with render.mjs.
"""

import math
from pathlib import Path

CANVAS = 1024
BODY = 824
MARGIN = (CANVAS - BODY) / 2
RADIUS = 185.4
SMOOTHING = 0.6


def squircle(x, y, size, radius, smoothing):
    """A rounded square whose corners ease into the edges (no curvature jump)."""
    p = min((1 + smoothing) * radius, size / 2)
    arc = 90 * (1 - smoothing)
    arc_len = math.sin(math.radians(arc / 2)) * radius * math.sqrt(2)
    alpha = (90 - arc) / 2
    p3_p4 = radius * math.tan(math.radians(alpha / 2))
    beta = 45 * smoothing
    c = p3_p4 * math.cos(math.radians(beta))
    d = c * math.tan(math.radians(beta))
    b = (p - arc_len - c - d) / 3
    a = 2 * b
    f = lambda v: f"{v:.2f}"
    w = h = size
    return " ".join([
        f"M {f(x + w - p)} {f(y)}",
        # top-right
        f"c {f(a)} 0 {f(a + b)} 0 {f(a + b + c)} {f(d)}",
        f"a {f(radius)} {f(radius)} 0 0 1 {f(arc_len)} {f(arc_len)}",
        f"c {f(d)} {f(c)} {f(d)} {f(b + c)} {f(d)} {f(a + b + c)}",
        f"L {f(x + w)} {f(y + h - p)}",
        # bottom-right
        f"c 0 {f(a)} 0 {f(a + b)} {f(-d)} {f(a + b + c)}",
        f"a {f(radius)} {f(radius)} 0 0 1 {f(-arc_len)} {f(arc_len)}",
        f"c {f(-c)} {f(d)} {f(-(b + c))} {f(d)} {f(-(a + b + c))} {f(d)}",
        f"L {f(x + p)} {f(y + h)}",
        # bottom-left
        f"c {f(-a)} 0 {f(-(a + b))} 0 {f(-(a + b + c))} {f(-d)}",
        f"a {f(radius)} {f(radius)} 0 0 1 {f(-arc_len)} {f(-arc_len)}",
        f"c {f(-d)} {f(-c)} {f(-d)} {f(-(b + c))} {f(-d)} {f(-(a + b + c))}",
        f"L {f(x)} {f(y + p)}",
        # top-left
        f"c 0 {f(-a)} 0 {f(-(a + b))} {f(d)} {f(-(a + b + c))}",
        f"a {f(radius)} {f(radius)} 0 0 1 {f(arc_len)} {f(-arc_len)}",
        f"c {f(c)} {f(-d)} {f(b + c)} {f(-d)} {f(a + b + c)} {f(-d)}",
        "Z",
    ])


body = squircle(MARGIN, MARGIN, BODY, RADIUS, SMOOTHING)
top, bottom = MARGIN, MARGIN + BODY
horizon = 598
sun_r = 196

# Reflections on the water: shorter and fainter toward the viewer.
ripples = "\n".join(
    f'    <rect x="{512 - w / 2:.1f}" y="{y}" width="{w}" height="{h}" rx="{h / 2}" '
    f'fill="url(#ripple)" opacity="{o}"/>'
    for y, w, h, o in [
        (628, 330, 13, 0.95),
        (664, 244, 12, 0.8),
        (698, 170, 11, 0.62),
        (730, 108, 10, 0.46),
        (760, 56, 9, 0.32),
    ]
)

# A few stars, faint; they vanish at small sizes, as they should.
stars = "\n".join(
    f'    <circle cx="{x}" cy="{y}" r="{r}" fill="#fff" opacity="{o}"/>'
    for x, y, r, o in [
        (256, 238, 3.2, 0.55), (340, 176, 2.4, 0.4), (704, 214, 3.0, 0.5),
        (786, 300, 2.2, 0.35), (612, 158, 2.2, 0.35), (198, 356, 2.0, 0.3),
    ]
)

svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{CANVAS}" height="{CANVAS}" viewBox="0 0 {CANVAS} {CANVAS}">
  <!-- Generated by make_svg.py: Sunna's app icon on Apple's macOS icon grid. -->
  <defs>
    <clipPath id="body"><path d="{body}"/></clipPath>
    <clipPath id="sky"><rect x="0" y="0" width="{CANVAS}" height="{horizon}"/></clipPath>
    <linearGradient id="night" x1="0" y1="{top}" x2="0" y2="{bottom}" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#2a2d5c"/>
      <stop offset="0.5" stop-color="#191a3a"/>
      <stop offset="1" stop-color="#0b0b16"/>
    </linearGradient>
    <radialGradient id="dawn" cx="512" cy="{horizon}" r="430" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#ff9d57" stop-opacity="0.75"/>
      <stop offset="0.45" stop-color="#e2587a" stop-opacity="0.28"/>
      <stop offset="1" stop-color="#6f3fb0" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="sun" x1="0" y1="{horizon - sun_r}" x2="0" y2="{horizon}" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#fff7dc"/>
      <stop offset="0.5" stop-color="#ffd07a"/>
      <stop offset="1" stop-color="#ff8448"/>
    </linearGradient>
    <linearGradient id="water" x1="0" y1="{horizon}" x2="0" y2="{bottom}" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#241a3f"/>
      <stop offset="1" stop-color="#08080f"/>
    </linearGradient>
    <linearGradient id="line" x1="{MARGIN}" y1="0" x2="{bottom}" y2="0" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#ffd9a3" stop-opacity="0"/>
      <stop offset="0.25" stop-color="#ffd9a3" stop-opacity="0.75"/>
      <stop offset="0.5" stop-color="#fff1d6"/>
      <stop offset="0.75" stop-color="#ffd9a3" stop-opacity="0.75"/>
      <stop offset="1" stop-color="#ffd9a3" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="ripple" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#ff9a55" stop-opacity="0.2"/>
      <stop offset="0.5" stop-color="#ffc98a"/>
      <stop offset="1" stop-color="#ff9a55" stop-opacity="0.2"/>
    </linearGradient>
    <linearGradient id="sheen" x1="0" y1="{top}" x2="0" y2="{top + 420}" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#fff" stop-opacity="0.14"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
      <feDropShadow dx="0" dy="10" stdDeviation="12" flood-color="#000" flood-opacity="0.38"/>
    </filter>
    <filter id="blur" x="-50%" y="-50%" width="200%" height="200%">
      <feGaussianBlur stdDeviation="34"/>
    </filter>
  </defs>

  <!-- body, with the shadow the macOS grid leaves room for -->
  <path d="{body}" fill="url(#night)" filter="url(#shadow)"/>
  <g clip-path="url(#body)">
    <rect x="0" y="0" width="{CANVAS}" height="{horizon}" fill="url(#dawn)"/>
{stars}
    <!-- the sun's glow, then the sun, above the horizon only -->
    <g clip-path="url(#sky)">
      <circle cx="512" cy="{horizon}" r="{sun_r + 34}" fill="#ffb15e" opacity="0.55" filter="url(#blur)"/>
      <circle cx="512" cy="{horizon}" r="{sun_r}" fill="url(#sun)"/>
    </g>
    <rect x="0" y="{horizon}" width="{CANVAS}" height="{bottom - horizon}" fill="url(#water)"/>
{ripples}
    <rect x="{MARGIN}" y="{horizon - 3}" width="{BODY}" height="6" rx="3" fill="url(#line)"/>
    <rect x="0" y="0" width="{CANVAS}" height="{CANVAS}" fill="url(#sheen)"/>
  </g>
  <!-- a hairline edge, lighter at the top, like Apple's icons -->
  <path d="{body}" fill="none" stroke="url(#sheen)" stroke-width="3"/>
</svg>
"""

Path(__file__).with_name("icon.svg").write_text(svg)
print("wrote icon.svg")
